In [8]:
import pandas as pd
import numpy as np

Series

In [2]:
S = pd.Series([1 ,143 , 2.5 , 3.14 , 'Nemo']) #In Pandas we have two types of classes to handle the Data  
S                                             # Series & DataFrame

0       1
1     143
2     2.5
3    3.14
4    Nemo
dtype: object

DataFrame's

In [ ]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]] , columns = ["A","B","C"] ,index = ["X","Y","Z"])
df

   A  B  C
X  1  2  3
Y  4  5  6
Z  7  8  9

In [ ]:
# # df.index            # To show the Index od DataFrame in Our Case X,Y,Z
# df.info()           # To Show the Information of DataFrame
df.describe()       # Thsi Helps to Show the Some Math Info 
#                         # --> Count : no.of non missing values in each column
                          # --> Mean : Average 
                          # Standard Deviation : If mean is small then  SD  is Small-SD And If mean is Large then SD is Large-SD
                          # Min : Minimum value in column 
                          # 25% : 
                          # 50% :
                          # 75% : 
                          # Max : Maximum value's in column 

# # df.shape            # Gives the Shape of the Data in Rows And Columns

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

Working On a Real DataSet

In [9]:
Coffee = pd.read_csv('coffee.csv')
Coffee

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.70,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.70,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.70,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.90,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.70,Latte
...,...,...,...,...,...,...
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,25.96,Americano
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte

Accessing Data With Pandas

In [ ]:
# Coffee.head()             # To access the First 5 Rows of a DataSet only integer's

# Coffee.tail(10)           # To access the Last 5 Rows of a DataSet --- .tail(10) is used to get last 10 Rows 

# Coffee.sample(10)         # To get Random Rows of a DataSet 

# Coffee.loc["Money"]           # Loc is used to modify rows and columns in DF

In [27]:
Coffee.sort_values(["money"],ascending=False)

,date,datetime,cash_type,card,money,coffee_name
46,2024-03-07,2024-03-07 10:08:58.945,cash,NaN,40.00,Latte
232,2024-04-05,2024-04-05 15:30:50.383,cash,NaN,40.00,Latte
233,2024-04-05,2024-04-05 15:54:15.768,cash,NaN,40.00,Cappuccino
235,2024-04-05,2024-04-05 16:17:43.975,cash,NaN,40.00,Cocoa
89,2024-03-12,2024-03-12 10:15:00.297,cash,NaN,40.00,Latte
...,...,...,...,...,...,...
1271,2024-08-14,2024-08-14 11:39:07.882,card,ANON-0000-0000-0095,18.12,Espresso
1193,2024-08-07,2024-08-07 13:11:16.155,card,ANON-0000-0000-0469,18.12,Espresso
1200,2024-08-08,2024-08-08 08:46:36.204,card,ANON-0000-0000-0141,18.12,Espresso
1581,2024-09-17,2024-09-17 12:38:33.768,card,ANON-0000-0000-0628,18.12,Espresso
1027,2024-07-24,2024-07-24 14:45:49.766,card,ANON-0000-0000-0012,18.12,Espresso

Filtering Data

In [ ]:
Coffee.loc[Coffee['money'] > 20 , ['coffee_name','money' ]]  # Without Condition

Coffee.loc[(Coffee['money'] > 20 ) & (Coffee['coffee_name'] == 'Latte' )]   # With Condition 

Coffee[Coffee['coffee_name'].isin(["Espresso"])]

,date,datetime,cash_type,card,money,coffee_name
31,2024-03-04,2024-03-04 14:04:37.734,card,ANON-0000-0000-0022,24.00,Espresso
61,2024-03-09,2024-03-09 12:05:15.559,card,ANON-0000-0000-0038,24.00,Espresso
77,2024-03-10,2024-03-10 11:19:20.764,card,ANON-0000-0000-0045,24.00,Espresso
100,2024-03-13,2024-03-13 12:34:30.315,cash,NaN,25.00,Espresso
102,2024-03-13,2024-03-13 15:40:22.261,card,ANON-0000-0000-0053,24.00,Espresso
...,...,...,...,...,...,...
3551,2025-03-18,2025-03-18 16:23:20.622,card,ANON-0000-0000-1203,21.06,Espresso
3576,2025-03-19,2025-03-19 18:30:44.007,card,ANON-0000-0000-1302,21.06,Espresso
3577,2025-03-19,2025-03-19 18:31:25.990,card,ANON-0000-0000-1303,21.06,Espresso
3586,2025-03-20,2025-03-20 14:21:41.901,card,ANON-0000-0000-1290,21.06,Espresso
3626,2025-03-22,2025-03-22 15:57:58.183,card,ANON-0000-0000-1302,21.06,Espresso

Adding Columns

In [32]:
Coffee['Taste'] = 'Good or Bad'
Coffee

# Coffee.insert(8, "coffe_id" , np.where('latte' == 101,'Cappuccino' == 102,'Americano' == 103,"Hot Chocolate" == 104 ))
# Coffee

,date,datetime,cash_type,card,money,coffee_name,Taste
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,32.34,Latte,Good or Bad
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.70,Hot Chocolate,Good or Bad
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.70,Hot Chocolate,Good or Bad
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.90,Americano,Good or Bad
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.70,Latte,Good or Bad
...,...,...,...,...,...,...,...
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino,Good or Bad
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa,Good or Bad
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa,Good or Bad
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,25.96,Americano,Good or Bad
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte,Good or Bad

Updating Columns

In [ ]:
# Coffee.loc[0,'money'] = 32.34         # --> Updating at a specifice position
# Coffee

# Coffee['Taste'] = Coffee['Taste'] + ' or yum'
# Coffee

,date,datetime,cash_type,card,money,coffee_name,Taste
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,32.34,Latte,Good or Bad yum or yum
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.70,Hot Chocolate,Good or Bad yum or yum
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.70,Hot Chocolate,Good or Bad yum or yum
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.90,Americano,Good or Bad yum or yum
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.70,Latte,Good or Bad yum or yum
...,...,...,...,...,...,...,...
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino,Good or Bad yum or yum
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa,Good or Bad yum or yum
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa,Good or Bad yum or yum
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,25.96,Americano,Good or Bad yum or yum
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte,Good or Bad yum or yum

Removing Columns

In [39]:
Coffee.drop( columns = ["Taste"], inplace= True)
Coffee

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,32.34,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.70,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.70,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.90,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.70,Latte
...,...,...,...,...,...,...
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,25.96,Americano
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte

Missing Values

In [ ]:
print(Coffee.isnull())              # --> Isnull it is used to tell missing values (False = the Value is Present)
                                    # -->                                          (True = the value is Not Present)    
print(Coffee.isnull().sum())        # --> Sum is used to tell the no.of missing values in columns

       date  datetime  cash_type   card  money  coffee_name
0     False     False      False  False  False        False
1     False     False      False  False  False        False
2     False     False      False  False  False        False
3     False     False      False  False  False        False
4     False     False      False  False  False        False
...     ...       ...        ...    ...    ...          ...
3631  False     False      False  False  False        False
3632  False     False      False  False  False        False
3633  False     False      False  False  False        False
3634  False     False      False  False  False        False
3635  False     False      False  False  False        False

[3636 rows x 6 columns]
date            0
datetime        0
cash_type       0
card           89
money           0
coffee_name     0
dtype: int64